---
# file: roles/app/tasks/main.yml

- include: nginx.yml

- name: open port 80
  firewalld: service=http
  args:
    permanent: true 
    state: enabled 
    zone: public
  notify:
    - reload firewall rules