---
# file: roles/app/tasks/nginx.yml

- name: install passenger gem
  command: gem install passenger -v 4.0.56
  args:
    creates: /usr/local/bin/passenger-install-nginx-module

- name : install nginx and passenger
  command: /bin/bash -l -c "swapoff /swapfile; rm /swapfile; dd if=/dev/zero of=/swapfile bs=1024 count=1024k; mkswap /swapfile; swapon /swapfile; passenger-install-nginx-module --auto --prefix=/opt/nginx --auto-download --languages ruby; swapoff /swapfile; rm /swapfile"
  args:
    creates: /opt/nginx/sbin/nginx

- name: send nginx conf
  template: src=../templates/nginx.conf.j2 dest=/opt/nginx/conf/nginx.conf
  args:
    mode: 0644
  tags: nginx
  notify:
    - restart nginx

- name: send nginx service
  copy: src=../files/nginx.service dest=/etc/systemd/system/nginx.service
  args:
    mode: 0644
  tags: nginx
  notify:
    - reload services

- name: start nginx service
  service: name=nginx state=started
  args:
    enabled: true
  tags: nginx

- name: logrotate nginx / rails
  template: src=../templates/app.logrotate.j2 dest=/etc/logrotate.d/appnginx
  args:
    mode: 0644
  tags: nginx
